version: "3.5"

services:
  vzlogger:
    image: ccs1/volkszahler-fritzapi:latest
    build:
      context: ./
      dockerfile: ./component/vzlogger/Dockerfile
    volumes:
      # mount the full api directory for development
      - "./api:/app/api"
      - "./component/vzlogger/vzlogger.json:/etc/vzlogger.conf"
    restart: always