version: "3.5"

services:
  fritzapi:
    build:
      context: ./component/fritzapi/
    volumes:
    - ".:/app"
  vzlogger:
    build:
      context: ./component/vzlogger/
    ports:
      - "8080:8080"
    volumes:
    - "./api:/app/api"
    - "./component/vzlogger/vzlogger.json:/etc/vzlogger.conf"