version: "3.5"

services:
  vzlogger:
    build:
      context: ./component/vzlogger/
    volumes:
    - "./api:/app/api"
    - "./component/vzlogger/vzlogger.json:/etc/vzlogger.conf"
    restart: always