# https://github.com/marketplace/actions/build-and-push-docker-images
name: docker-build

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: ccs1/volkszahler-fritzapi:latest
      -
        name: Build and push PR
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:component/vzlogger/"
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ccs1/volkszahler-fritzapi:pr_${{github.event.number}}_${{github.sha}}